### ISSUE TITLE
7 Dwarfs errors - potentially related to RFLIB Feature Switch CMDT call in validation rule...

### ISSUE THREAD

**Issue by kurtfairfield** [j-fischer/rflib#34]
**Describe the bug**
Getting intermittent Seven Dwarf errors (DOC, SLEEPY, GRUMPY) on unit tests in sandboxes, and now in PROD. SF Support is on the case...

appears to be associated with a Validation rule on custom object that checks a Feature Switch.

> System.DmlException: Insert failed. First exception on row 0; first error: FIELD_CUSTOM_VALIDATION_EXCEPTION, Validation Formula "Manage_PO_Status_Transitions" Invalid (common.exception.SfdcSqlException: ORA-30006: resource busy; acquire with WAIT timeout expired
> ORA-06512: at "GRUMPY.CCUSTOMMETADATA", line 71
> ORA-06512: at "GRUMPY.CCUSTOMMETADATA", line 92
> ORA-06512: at line 1
> 
> SQLException while executing plsql statement: {call cCustomMetadata.lock_row_for_save(?)}(m021K000000KNqB)): []
> Class.CSHandler_BlockDeactivationTest.testDataSetup: line 86, column 1

**Version**
2.3 (and 1.1 and 1.1), no mods

**Code Snippets**
validation rule call - $CustomMetadata.rflib_Feature_Switch__mdt.Allow_Any_PO_Status_Update.Turned_On__c

**Expected behavior**
no unit test errors

**Screenshots**
If applicable, add screenshots to help explain your problem, i.e. Chrome Dev Console.

**Desktop (please complete the following information):**
 - OS: [e.g. iOS] W10
 - Browser [e.g. chrome, safari] chrome
 - Version [e.g. 22] - Version 91.0.4472.124 (Official Build) (64-bit)

**Additional context**
intermittent, sometimes some tests fail, sometimes others don't

likely not an RFLIB bug (see what SF support says after checking the PROD server logs). I was just wondering if you had seen this before....

**Comment by j-fischer** [comment]
Thanks for posting @kurtfairfield !
I have not seen this issue before. The error message is a Java error, which indicates a low-level error within the Salesforce platform. Please keep me posted and let me know if there is anything I can do to help. For now, I am waiting to hear what Salesforce has to say.

**Comment by kurtfairfield** [comment]
Okay thanks, just checking.  We can close this case, and if it is
related to RFLIB, we can reopen, or address in some other way. I doubt it
is, but I have no visibility... have to wait and see what SF Support comes
back with...

Kurt Fairfield
 250 589 6263
 ***@***.***
 www.fesi.ca
<https://app.salesforceiq.com/r?target=60e7a7755f0cf518dcd5899f&t=AFwhZf3zRTZqAkUj0lMmNclre_64mnIrasAaanG8zao-_E7lWmHEQA6FQjsykvOA6EGxvKq451losxV3WSJUIYbwKG-SNVuHODmDzCgui5qP-A2v6zTbhBHVHF5er8T8TBuN4gGEEwKU&url=http%3A%2F%2Fwww.fesi.ca%2F>

*   A Registered Salesforce Partner*

**Comment by j-fischer** [comment]
Thanks, closing it for now, but it would be great if you could share the outcome of the case, so that others have an idea if they encounter the same issue. 
Thanks

**Comment by kurtfairfield** [comment]
will do

Kurt Fairfield
 250 589 6263
 ***@***.***
 www.fesi.ca
<https://app.salesforceiq.com/r?target=60e894568fbe403780212c70&t=AFwhZf0wjlnYxhpFwePU0X4khk4DaDm1yrDRArp-T7hgjyAaMr41RhkRFSJsjGoKv8UGGdEj6xLyMEAlM7MNv3mgrvQWO8iRu8N9BKoccDH-NnRZtYDGc1BeHYm4jxpV1NpdFaTaUhfY&url=http%3A%2F%2Fwww.fesi.ca%2F>

*   A Registered Salesforce Partner*

**Comment by kurtfairfield** [comment]
# Root Cause Identified
## CMDT/Validation Rule Record Lock is a Known Issue with Salesforce
## Workaround Provided

So after a bit of a battle with Salesforce Support, where I was rebuffed twice, but ended up getting acknowledgment that is was a known issue in the backend, that they are apparently working to resolve.

[https://trailblazer.salesforce.com/issues_view?id=a1p4V000000KUP7QAO](https://trailblazer.salesforce.com/issues_view?id=a1p4V000000KUP7QAO)

The issue is specifically related to accessing CMDT in a validation rule (for example: RFLIB Feature Switches). The issue happens when tests run async and there is record lock on the CMDT record.  Known issue by Salesforce, being worked on, apparently. Not sure why CMDT record needs a row lock for read access only...

The work proposed by Salesforce Support is as follows:

1. Turn off parallel testing - via the Salesforce Setup UI in PROD
2. Disable asynchronous testing - via Dev Console/IDE/CLI etc.
3. Set Debug logs for Validation Rules to NONE for the user running the tests - via Dev Console/IDE/CLI etc.

NOTE: there are two additional steps provided, compared to the Knowledge article above. I found that the issue was resolved by clearing debug logging on Validation rules, so others may also be able to do so, and run asynchronous tests without issue.

So, while not a bug/issue with RFLIB, perhaps should be noted in the How To Guide for Feature Switches when using with Validation Rules, to set log level to NONE, if you are getting visits from any of the Seven Dwarves...
