### ISSUE TITLE
Unit Tests Failing

### ISSUE THREAD

**Issue by kurtfairfield** [j-fischer/rflib#39]
**Describe the bug**
All of a sudden, 12 RFLIB unit tests started failing in one of my orgs on NA154

**Version**
RFLIB 2.7 (unmodified)
RFLIB-FS 1.2 (unmodified)
RFLIB-TF 1.3 (unmodified)

**Code Snippets**

<html>
<body>

Error message: | System.DmlException: Insert failed. First exception on row 0; first error: UNABLE_TO_LOCK_ROW, unable to obtain exclusive access to this record: []
-- | --
Stack trace: | Class.rflib_UserFactory.Builder.persistWithPermissions: line 89, column 1 Class.rflib_UserFactory.insertWithCustomPermissionAndRetrieve: line 39, column 1 Class.rflib_TriggerManagerTest: line 42, column 1

</body>
</html>

**Expected behavior**
Day prior unit tests were fine, no significant metadata or data changes in the org, expect that they would keep passing

Stack trace shows error while trying to create a user with Standard User Profile, and the Custom Permission of Bypass All Triggers

**Screenshots**
From GearSet automated testing history

![image](https://user-images.githubusercontent.com/18200424/137487284-f1694ab3-e4b7-4e4a-b8a8-0f45b726f94f.png)

System Audit Trail showing before and after tests started failing - tests failed at 12:00 - 12:15 am PST on Oct 14, 2021

![image](https://user-images.githubusercontent.com/18200424/137487811-a58224c3-eff4-4680-bb2b-2dd6f3a58ab2.png)

Installed Packages and dates

![image](https://user-images.githubusercontent.com/18200424/137488124-cd5b9233-2b47-463c-b4ee-56f1d0f1f1b6.png)

NA154 Server Maintenance Updates

![image](https://user-images.githubusercontent.com/18200424/137488509-b62a85f9-9e88-44cb-a347-f332922eab87.png)

**Desktop (please complete the following information):**
 - OS: - W10
 - Browser - Chrome
 - Version - 94.0.4606.81 (Official Build) (64-bit)

**Smartphone (please complete the following information):**
n/a

**Additional context**

Running daily unit testing in other org with different versioned RFLIB installed packages, no issues reported there.

RFLIB 2.3 (unmodified)
RFLIB-FS 1.1 (unmodified)
RFLIB-TF 1.1 (unmodified)

![image](https://user-images.githubusercontent.com/18200424/137489421-dabcafb6-546f-46dd-a5fb-52de14ce5209.png)

rflib_TriggerMangerTest.cls runs fine on its own from Intellij, but fails when run All tests from Dev Console (run async unchecked). Perhaps issue with synchronous running of tests.

This org is on a special Canadian AWS version, which is due to be swapped out to a Hyperforce Server on Oct 17, 2021, but has not happened yet.

**Comment by j-fischer** [comment]
@kurtfairfield are those unit tests still failing? 

I am closing this ticket for now but please feel free to re-open it if you still encounter any issues. 

Thanks
