### ISSUE TITLE
Minor Issue : BEM Notification Deprecating -- in CSS in the Summer '21 release

### ISSUE THREAD

**Issue by kurtfairfield** [j-fischer/rflib#44]
Read this in the W22 Dev Maintenance module, and wondered if this had any impact on RFLIB.

From - [W22 Dev Maintenance Trailhead Module](https://trailhead.salesforce.com/en/content/learn/modules/platform-developer-i-certification-maintenance-winter-22/learn-whats-new-for-platform-developers-22)

> BEM Notation with Double Dashes Is Being Deprecated
> The BEM notation with double dashes (--) in Lightning Design System will be deprecated in Summer ’21 and replaced by the single underscore notation (_).
> 
> Why: Double dashes are not supported in XML files that include comments. This notation change was first announced in Salesforce Lightning Design System (SLDS) Release 2.3.1 on May 25, 2017, and announced again in the Winter ’21 release notes.
> 
> How: In Summer ’21, all BEM notation with double dashes will no longer be available in SLDS 2.13.0 and later versions. For your styles to continue working with SLDS 2.13.0 and later versions, replace -- with _ in your CSS. For example, replace slds-button--brand with slds-button_brand. If you’re using SLDS 2.12.2 and earlier versions, your styles continue to work as no changes have been made to those versions.
> 
> If you develop using VSCode, use the SLDS Validator extension to fix the BEM notation in your code. The extension is available as a standalone but also as part of the Salesforce Extension Pack.

I notice there is a bit of double dash notation in rflibLogEventList.css, not sure if this deprecation is applicable here or just for SLDS specific tags only, but thought I would mention it in case. Better to know before...

```
 .selected {
    background-color: var(--lwc-colorBackgroundRowNew);
}

.slds-table_striped tbody tr:nth-of-type(even).selected > td {
    background-color: var(--lwc-colorBackgroundRowNew);
 }
```

**Comment by j-fischer** [comment]
Thanks for opening this issue, @kurtfairfield , I haven't had the time to check the release notes yet. I will definitely take a look. Will post an update here shortly.

**Comment by j-fischer** [comment]
Hi @kurtfairfield , thanks again for opening this issue. 

After reviewing the documentation, my understanding is that the BEM issue refers to CSS class names and the way they are referenced in .html, .cmp, and xml files. Here, the double dashes (--) need to be removed and replaced with a single underscore (_). 

As you probably found yourself, there are no instances of -- in CSS class names in any of RFLIB's html files. 

The references that you found are standard CSS variable references to Salesforce SLDS Design Tokens, which are following the [standard syntax as described in the documentation](https://developer.mozilla.org/en-US/docs/Web/CSS/var()). 

I therefore believe that RFLIB is already conforming with the BEM update that Salesforce released and will therefore close this thicket. 

Again, please do not hesitate to open such issues in the future. I cannot stay on top of all of those things myself, so the help of the community is of immense value to keep the high quality that I aspire to. 

Cheers!
