### ISSUE TITLE
FeatureSwitchTest fails when there is a trigger on User

### ISSUE THREAD

**Issue by mikbranchaud** [j-fischer/rflib#50]
I had an issue with this test class.  It seems that when the User is created and you have a trigger on the User object, the All_Triggers feature switch that comes with the trigger framework is evaluated.  The process of evaluating that trigger does a get of directPublicGroupAssociations which then contains of groups of the user running the test. 

The in tests that interrogate this (testGetAllScopedValues and testGroupSwitch) the absence of the setup associated group fails the test.  I fixed this for myself by making the getter of directPublicGroupAssociations testVisible and setting it to null in these test classes inside the system.runas

The trigger framework be explicitly be mocked in this test class instead?

_Originally posted by @mikbranchaud in https://github.com/j-fischer/rflib/pull/19#issuecomment-1083081580_

**Comment by j-fischer** [comment]
Hi @mikbranchaud , first of all, sorry for missing this comment on issue #19, 

Next, would you be able to share your code on how you fixed the issue. I am not 100% sure I followed the exact context of the test failure, so I am hoping that the code would help. 

I planning a patch sometime soon for another issue, it would be great to get this one in as well. 

As always, thanks for the support!

**Comment by j-fischer** [comment]
@mikbranchaud Fixed in RFLIB-FS 1.2.1
Thanks for submitting this ticket.
