### ISSUE TITLE
Log Monitor not showing whole log data in namespace org

### ISSUE THREAD

**Issue by shyamvarshney** [j-fischer/rflib#53]
When I am using the log monitor in the developer org , the log data created is fine and completed. But when i am using log monitor in a namespace Org , the log data is not coming as whole. The script I am running is as follows : 
rflib_Logger LOGGER = rflib_LoggerUtil.getFactory().createLogger('Demo class');
rflib_LogTimer logtimer = rflib_LoggerUtil.startLogTimer(LOGGER,300,'Handling Demo class');
try{
LOGGER.info('TRYING FINDING INPUT VALUES');
LOGGER.warn('Values and fields missing');
}
catch(Exception e){
LOGGER.error('Anonymous error occured',e);
}
logtimer.done();
I am attaching screenshots for both , if anyone has solution for it , please help.
![capture 12](https://user-images.githubusercontent.com/98407305/161746642-6b7571e2-1bde-41dd-aaf2-1496450e8d90.PNG)
![Capture](https://user-images.githubusercontent.com/98407305/161746651-2a64fdc5-6938-43cb-9942-e4a1bd5a009e.PNG)
Capture 12 shows the namespace org data and capture shows the developer org data.

**Comment by prakash-concret** [comment]
In the namespace Org, you need to use the org namespace prefix for all custom fields of the platform event.
For the rflibLogEventViewer component
`<lightning-formatted-text value={logEvent.Log_Messages__c}>`
Need to update like:
`<lightning-formatted-text value={logEvent.namespaceprefix__Log_Messages__c}>`

**Comment by j-fischer** [comment]
@prakash-concret @shyamvarshney 
I added a page to the documentation for this scenario. I used your comment here and added what I thought needs to be changed as well. Could you validate the page and provide feedback in this ticket. Would love to make more edits based on your experience. 

https://github.com/j-fischer/rflib/wiki/Using-RFLIB-in-a-Managed-Package

Thanks a lot for using the library! 

Cheers
