### ISSUE TITLE
 Feature Switches with validation rules and Dynamic Lightning Pages

### ISSUE THREAD

**Issue by jdgirald** [j-fischer/rflib#68]
Hi, great library!

I was wondering if there are any guidelines for using Feature Switches with validation rules and Dynamic Lightning Pages.

Thanks

**Comment by j-fischer** [comment]
Hi @jdgirald , thanks for the question, I am glad you enjoy using RFLIB. 

To answer your request, Feature Switches can be used in Validation Rules, but there is a limitation that you need to call the switch by its API name, which makes scoping extremely difficult. It's recommended to only use switches of a global scope in this case. Depending on your use case, Custom Permissions might also be a good option to consider to build more sophisticated validation rules. 

Lightning Pages (presumably visibility filter) do not support formulas yet, hence you can't use Feature Switches at the current time. However, I typically use Custom Permission to handle user group based visibility for certain components. 

I hope this helps. Please feel free to reopen if you have further questions. Thanks to your ticket, I updated the Wiki to adding a section for validation rules and adding more headers for easier navigation. 
https://github.com/j-fischer/rflib/wiki/Getting-Started-with-Feature-Switches

Cheers
